services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kontakt-db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'